Get the system timezone from debconf, insert it into airtime config

diff --git a/airtime-easy-install/DEBIAN/postinst b/airtime-easy-install/DEBIAN/postinst
--- a/airtime-easy-install/DEBIAN/postinst
+++ b/airtime-easy-install/DEBIAN/postinst
@@ -24,6 +24,23 @@ case "$1" in
     # Install the package signing key
     apt-key add $APT_KEY
 
+    # Get the system time zone
+    tmpfile=$(mktemp)
+     if [ -f "${tmpfile}" -a -w "${tmpfile}" ]; then
+      debconf-get-selections > "${tmpfile}"
+       set -- $(egrep '^tzdata[[:space:]]+tzdata/Areas[[:space:]]+select[[:space:]]+[^[:space:]]' "${tmpfile}")
+       while [ -n "$1" ]; do area="$1"; shift; done
+       set -- $(egrep "^tzdata[[:space:]]+tzdata/Zones/${area}[[:space:]]+select[[:space:]]+[^[:space:]]" "${tmpfile}")
+       while [ -n "$1" ]; do zone="$1"; shift; done
+       SYSTEMTIMEZONE="${area}/${zone}"
+       rm "${tmpfile}"
+     else
+      echo "error: failed to create tempfile" >&2
+     fi
+
+    # Insert the system time zone into the preseed file
+    sed -i "s:Etc/UTC:$SYSTEMTIMEZONE:g" /usr/share/airtime/debconf-selections
+
     echo "Now running airtime-easy-install..."
     mkdir -p /var/log/airtime
     nohup /usr/bin/airtime-easy-install > /var/log/airtime/airtime-easy-install &
